name: publish
on: [push]
jobs:
publish-php-basic-image:
runs-on: ubuntu-22.04
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: likem.one
password: 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
- name: Build the PHP image 72 image
run: |
       docker build . --tag ghcr.io/0on6/php-basic:latest
       docker run ghcr.io/0on6/php-basic:latest
       docker push ghcr.io/0on6/php-basic:latest
